# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"terminal - floating" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = "🗋"
"libreoffice" = ""
"nvim" = ""
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = "🗎"
"emacs" = "𝓔"
"spotify" = ""
"steam" = ""
"gimp" = ""
"discord" = ""
"files" = "k"
"openscad" = ""
"cura" = "⎙"
"swappy" = "🖵"

[other]
fallback_icon = "‽"
deduplicate_icons = true
separator = ": "
